services:

  inkmanager-db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: inkdb
      POSTGRES_PASSWORD: senhadodb
    ports:
      - "5432:5432"

volumes:
  postgres-data: