"""create tables

Revision ID: 6e46f6438bb8
Revises: 
Create Date: 2024-10-30 09:22:19.841792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e46f6438bb8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inks',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('neddles',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.Enum('round_liner', 'round_shader', 'magnum', 'magnum_rounded', name='needlemodel'), nullable=False),
    sa.Column('size', sa.Enum('n08_01', 'n08_03', 'n08_05', 'n08_07', 'n08_09', 'n08_11', 'n08_13', 'n08_14', 'n08_15', 'n08_17', 'n08_19', 'n08_21', 'n08_23', 'n08_25', 'n08_27', 'n10_01', 'n10_03', 'n10_05', 'n10_07', 'n10_09', 'n10_11', 'n10_13', 'n10_14', 'n10_15', 'n10_17', 'n10_19', 'n10_21', 'n10_23', 'n10_25', 'n10_27', 'n12_01', 'n12_03', 'n12_05', 'n12_07', 'n12_09', 'n12_11', 'n12_13', 'n12_14', 'n12_15', 'n12_17', 'n12_19', 'n12_21', 'n12_23', 'n12_25', 'n12_27', name='needlesize'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    op.drop_table('neddles')
    op.drop_table('inks')
    # ### end Alembic commands ###
